name: build
on: [push]
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    - name: Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: make lint
    - name: Test
      run: make test
