name: build
on: [push]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: make lint
    - name: Test
      run: make test
